"""Native, editable Excel charts for the Space RDS results workbook.

Senior-review chart pack. The Charts tab is intentionally ordered as:
1. Group risk shape
2. Manufacturer concentration
3. Gross Δ% by entity & scenario
4. Portfolio in-force exposure bridge
5+. Reinsurance / XoL supporting charts

Every chart is a native Excel chart linked to formula-backed tables on Chart Data.
No chart values are hard-coded: Chart Data links to Summary, Space Weather,
Changes and Portfolio sheets, so the visuals update when the workbook updates.
"""
from __future__ import annotations

from openpyxl.chart import BarChart, LineChart, Reference
from openpyxl.chart.axis import ChartLines
from openpyxl.chart.label import DataLabelList
from openpyxl.chart.marker import Marker, DataPoint
from openpyxl.chart.shapes import GraphicalProperties
from openpyxl.drawing.line import LineProperties
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.worksheet.properties import PageSetupProperties
from openpyxl.utils import get_column_letter

# ---- palette ----------------------------------------------------------------
NAVY = "1B3A5C"; NAVY_LT = "5B86B0"; SKY = "9CC0E0"
GREEN = "2D6A3C"; AMBER = "9A6410"; RED = "C0392B"
# Entity categorical palette — colour-blind-safe, validated (validate_palette.js:
# lightness/chroma/CVD-separation/contrast all PASS). Fixed hue order per entity,
# never cycled; colour follows the entity, not its rank.
PAL_FIHL = "1F6FB2"       # blue    — group / consolidated (primary)
PAL_FUL = "C46A10"        # orange  — operating entity
PAL_FIBL = "328E6E"       # green   — internal RI receiver
PAL_FIID = "9B4FA0"       # purple  — operating entity
PAL_GROSS = "D9DEE7"      # soft grey-blue — gross (light end of the gross→net pair)
PAL_NET = "1E3B5F"        # deep navy      — net   (dark end of the pair)
PAL_LINE = "5A6B7D"       # slate overlay line (cumulative %, retention) — neutral, not a categorical hue
PAL_POS = "1F6FB2"        # positive exposure movement (blue)
PAL_NEG = "1F2933"        # negative exposure movement (ink)
PAL_TOTAL = "1B3A5C"      # opening / closing anchor bars (navy)
PAL_LAYER = "6382A8"
PAL_ABOVE = "C0392B"      # above-tower breach — reserved status red

INK = "1F2933"; SOFT = "6B7785"; RULE = "DCE3EA"; CREAM = "EEF3F8"
HDRTXT = "FFFFFF"; BLUE_INPUT = "0000CC"
_FB = "Calibri"
F_TITLE = Font(name=_FB, size=17, bold=True, color=NAVY)
F_SUB = Font(name=_FB, size=10, color=SOFT)
F_SECT = Font(name=_FB, size=12, bold=True, color=NAVY)
F_HDR = Font(name=_FB, size=9, bold=True, color=HDRTXT)
F_CELL = Font(name=_FB, size=10, color=INK)
F_INPUT = Font(name=_FB, size=10, color=BLUE_INPUT)
F_CAP = Font(name=_FB, size=9, italic=True, color=SOFT)
FILL_HDR = PatternFill("solid", start_color=NAVY)
FILL_ALT = PatternFill("solid", start_color=CREAM)
FILL_INPUT = PatternFill("solid", start_color="FFF8E1")
MONEY = '#,##0;(#,##0);"–"'
MONEY_M = '#,##0,,"m";(#,##0,,"m");"–"'
PCT = '0.0%'
SCEN_ORDER = ["Proton Flare", "Space Weather", "Generic Defect", "Space Debris", "Max Risk"]
ENTS = ["FIHL", "FUL", "FIBL", "FIID"]
ENTITY_ROW0 = {"FIHL": 7, "FUL": 15, "FIID": 23, "FIBL": 31}
DEFAULT_XOL = {
    "FUL": {"deductible": 50_000_000, "limit": 245_000_000},
    "FIID": {"deductible": 7_500_000, "limit": 72_500_000},
}

# ---- helpers ----------------------------------------------------------------
def _sheet_ref(name: str) -> str:
    return "'" + str(name).replace("'", "''") + "'"


def _safe_delete(wb, sheet_name):
    if sheet_name in wb.sheetnames:
        del wb[sheet_name]


def _locate_entity_rows(ws):
    found = {}
    for r in range(1, (ws.max_row or 40) + 1):
        v = ws.cell(row=r, column=2).value
        if v in ENTITY_ROW0 and v not in found:
            found[v] = r + 2
    return {**ENTITY_ROW0, **found}


def _find_row(ws, label, col=2, default=None, exact=True):
    for r in range(1, ws.max_row + 1):
        v = ws.cell(row=r, column=col).value
        if exact and v == label:
            return r
        if not exact and isinstance(v, str) and label in v:
            return r
    return default


def _find_portfolio_bridge_rows(ws):
    """Locate the live portfolio bridge rows on Portfolio tab.

    Returns source rows for opening/new/run-off/revaluation/closing. The row
    labels are generated by the pipeline and remain formula-linked; this helper
    only locates the rows so Chart Data can point to them.
    """
    labels = {
        "Opening": ["Opening in-force"],
        "Written": ["+ New business", "Written"],
        "Expired": ["− Run-off / expiry", "- Run-off / expiry", "Expired", "Dropped"],
        "Renewed": ["± Revaluation", "Renewed", "Revaluation"],
        "Closing": ["Closing in-force", "Closing"],
    }
    out = {}
    for key, patterns in labels.items():
        for r in range(1, ws.max_row + 1):
            v = ws.cell(row=r, column=2).value
            if isinstance(v, str) and any(p in v for p in patterns):
                out[key] = r
                break
    # sensible generated-workbook defaults
    return {
        "Opening": out.get("Opening", 9),
        "Written": out.get("Written", 10),
        "Expired": out.get("Expired", 11),
        "Renewed": out.get("Renewed", 12),
        "Closing": out.get("Closing", 13),
    }


def _hdr_row(ws, r, c0, headers):
    for j, h in enumerate(headers):
        cell = ws.cell(row=r, column=c0 + j, value=h)
        cell.font = F_HDR
        cell.fill = FILL_HDR
        cell.alignment = Alignment(horizontal="left" if j == 0 else "right", vertical="center")
    return r + 1


def _alt_row(ws, r, c0, c1, alt=False):
    for c in range(c0, c1 + 1):
        cell = ws.cell(row=r, column=c)
        cell.border = Border(bottom=Side(style="thin", color=RULE))
        if alt:
            cell.fill = FILL_ALT


def _style_axes(chart, y_title="$m", y_fmt=MONEY_M):
    chart.x_axis.delete = False
    chart.y_axis.delete = False
    chart.y_axis.title = y_title
    chart.y_axis.numFmt = y_fmt
    chart.y_axis.majorGridlines = ChartLines()
    chart.y_axis.majorGridlines.spPr = GraphicalProperties()
    chart.y_axis.majorGridlines.spPr.line = LineProperties(solidFill=RULE, w=6350)
    chart.x_axis.majorGridlines = None


def _colour(series, rgb, line=None):
    series.graphicalProperties = GraphicalProperties(solidFill=rgb)
    # Bars (line=None) get a thin white edge so adjacent/stacked fills read as
    # separate marks (2px surface-gap spec); line series keep their own colour.
    edge = line if line is not None else "FFFFFF"
    w = 9525 if line is not None else 12700
    series.graphicalProperties.line = LineProperties(solidFill=edge, w=w)


def _safe_num(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def _caption(ws, row, text):
    c = ws.cell(row=row, column=2, value=text)
    c.font = F_SECT
    c.alignment = Alignment(wrap_text=True, vertical="top")
    ws.merge_cells(start_row=row, start_column=2, end_row=row + 1, end_column=11)
    ws.row_dimensions[row].height = 24
    ws.row_dimensions[row + 1].height = 18


def _note(ws, row, text):
    c = ws.cell(row=row, column=3, value=text)
    c.font = F_CAP
    c.alignment = Alignment(wrap_text=True, vertical="top")
    ws.merge_cells(start_row=row, start_column=3, end_row=row + 1, end_column=11)
    ws.row_dimensions[row].height = 18
    ws.row_dimensions[row + 1].height = 18

# ---- Chart Data tables ------------------------------------------------------
def _table_group_shape(cd, summary_name, r0, rows):
    cd.cell(row=r0, column=2, value="1. Group risk shape — gross loss by entity & scenario").font = F_SECT
    h = _hdr_row(cd, r0 + 1, 2, ["Scenario", "FIHL", "FUL", "FIBL", "FIID"])
    sref = _sheet_ref(summary_name)
    for i, scen in enumerate(SCEN_ORDER):
        rr = h + i
        cd.cell(row=rr, column=2, value=scen).font = F_CELL
        for j, ent in enumerate(["FIHL", "FUL", "FIBL", "FIID"], start=3):
            sr = rows[ent] + i
            c = cd.cell(row=rr, column=j, value=f"={sref}!D{sr}")
            c.number_format = MONEY; c.font = F_CELL
        _alt_row(cd, rr, 2, 6, i % 2 == 0)
    return h, h + len(SCEN_ORDER) - 1


def _table_group_gross_net(cd, summary_name, r0, rows, binding=None):
    """FIHL (group) gross & net by scenario — the capital-basis risk shape."""
    cd.cell(row=r0, column=2,
            value="1. Group risk shape — gross vs net loss by scenario (FIHL)").font = F_SECT
    h = _hdr_row(cd, r0 + 1, 2, ["Scenario", "Gross", "Net"])
    sref = _sheet_ref(summary_name)
    for i, scen in enumerate(SCEN_ORDER):
        rr = h + i
        sr = rows["FIHL"] + i
        label = f"{scen}  \u25c6" if scen == binding else scen
        cd.cell(row=rr, column=2, value=label).font = F_CELL
        cd.cell(row=rr, column=3, value=f"={sref}!D{sr}").number_format = MONEY
        cd.cell(row=rr, column=4, value=f"={sref}!J{sr}").number_format = MONEY
        cd.cell(row=rr, column=3).font = F_CELL; cd.cell(row=rr, column=4).font = F_CELL
        _alt_row(cd, rr, 2, 4, i % 2 == 0)
    return h, h + len(SCEN_ORDER) - 1


def _table_pareto(cd, sw_name, sw_ws, r0, n=10):
    cd.cell(row=r0, column=2, value="2. Manufacturer concentration — Space Weather basis").font = F_SECT
    h = _hdr_row(cd, r0 + 1, 2, ["Bus manufacturer", "Exposure", "Cumulative %"])
    swref = _sheet_ref(sw_name)
    total_row = _find_row(sw_ws, "TOTAL", col=2, default=33, exact=False)
    total_ref = f"{swref}!$C${total_row}"
    for i in range(n):
        sr = 6 + i
        rr = h + i
        cd.cell(row=rr, column=2, value=f"={swref}!B{sr}").font = F_CELL
        cd.cell(row=rr, column=3, value=f"={swref}!C{sr}").number_format = MONEY
        cd.cell(row=rr, column=4, value=f"=IFERROR(SUM($C${h}:$C{rr})/{total_ref},0)").number_format = PCT
        cd.cell(row=rr, column=3).font = F_CELL; cd.cell(row=rr, column=4).font = F_CELL
        _alt_row(cd, rr, 2, 4, i % 2 == 0)
    return h, h + n - 1


def _table_delta(cd, changes_name, r0):
    cd.cell(row=r0, column=2, value="3. Gross Δ% by entity & scenario").font = F_SECT
    h = _hdr_row(cd, r0 + 1, 2, ["Scenario", "FIHL", "FUL", "FIBL", "FIID"])
    cref = _sheet_ref(changes_name)
    # Changes tab generated table is Scenario/FIHL/FUL/FIBL/FIID in B7:F13.
    for i in range(5):
        src = 8 + i
        rr = h + i
        cd.cell(row=rr, column=2, value=f"={cref}!B{src}").font = F_CELL
        for c in range(3, 7):
            src_col = get_column_letter(c)
            # Source cells are live numeric Δ% formulas (the ▲/▼ is just a number
            # format), so reference them directly; a no-data '–' coerces to 0.
            formula = f"=IF(ISNUMBER({cref}!{src_col}{src}),{cref}!{src_col}{src},0)"
            cell = cd.cell(row=rr, column=c, value=formula)
            cell.number_format = PCT; cell.font = F_CELL
        _alt_row(cd, rr, 2, 6, i % 2 == 0)
    return h, h + 4


def _table_exposure_bridge(cd, portfolio_name, portfolio_ws, r0):
    cd.cell(row=r0, column=2, value="4. Portfolio in-force exposure bridge").font = F_SECT
    h = _hdr_row(cd, r0 + 1, 2, ["Step", "Exposure movement"])
    pref = _sheet_ref(portfolio_name)
    rows = _find_portfolio_bridge_rows(portfolio_ws)
    # User-facing order requested: Q4 opening -> written/new -> renewed/revaluation -> expired/run-off -> Q1 closing.
    steps = [
        ("Opening", "Opening", rows["Opening"]),
        ("Written / new", "Written", rows["Written"]),
        ("Renewed / revaluation", "Renewed", rows["Renewed"]),
        ("Expired / run-off", "Expired", rows["Expired"]),
        ("Closing", "Closing", rows["Closing"]),
    ]
    for i, (label, _, src_row) in enumerate(steps):
        rr = h + i
        cd.cell(row=rr, column=2, value=label).font = F_CELL
        c = cd.cell(row=rr, column=3, value=f"={pref}!D{src_row}")
        c.number_format = MONEY; c.font = F_CELL
        _alt_row(cd, rr, 2, 3, i % 2 == 0)
    return h, h + len(steps) - 1


def _table_effectiveness(cd, summary_name, r0, entity, er0):
    cd.cell(row=r0, column=2, value=f"{entity} — gross vs net & retention").font = F_SECT
    h = _hdr_row(cd, r0 + 1, 2, ["Scenario", "Gross", "Ceded", "Net retained", "Retention %"])
    sref = _sheet_ref(summary_name)
    for i, scen in enumerate(SCEN_ORDER):
        sr = er0 + i; rr = h + i
        cd.cell(row=rr, column=2, value=scen).font = F_CELL
        cd.cell(row=rr, column=3, value=f"={sref}!D{sr}").number_format = MONEY
        cd.cell(row=rr, column=4, value=f"={sref}!D{sr}-{sref}!J{sr}").number_format = MONEY
        cd.cell(row=rr, column=5, value=f"={sref}!J{sr}").number_format = MONEY
        cd.cell(row=rr, column=6, value=f"=IFERROR(E{rr}/C{rr},0)").number_format = PCT
        for cc in range(3, 7): cd.cell(row=rr, column=cc).font = F_CELL
        _alt_row(cd, rr, 2, 6, i % 2 == 0)
    return h, h + len(SCEN_ORDER) - 1


def _table_tower(cd, summary_name, r0, entity, ded, limit, er0):
    cd.cell(row=r0, column=2, value=f"{entity} — XoL tower utilisation").font = F_SECT
    cd.cell(row=r0, column=8, value="Deductible").font = F_SUB
    cd.cell(row=r0, column=9, value=ded).number_format = MONEY
    cd.cell(row=r0 + 1, column=8, value="Limit").font = F_SUB
    cd.cell(row=r0 + 1, column=9, value=limit).number_format = MONEY
    for rr in (r0, r0 + 1):
        cd.cell(row=rr, column=9).font = F_INPUT; cd.cell(row=rr, column=9).fill = FILL_INPUT
    cd.cell(row=r0 + 2, column=8, value="Editable XoL assumptions from IGR XoL parameters.").font = F_CAP
    ded_ref = f"$I${r0}"; lim_ref = f"$I${r0 + 1}"
    h = _hdr_row(cd, r0 + 1, 2, ["Scenario", "Retained within deductible", "Ceded to XoL", "Above tower", "Attachment"])
    sref = _sheet_ref(summary_name)
    for i, scen in enumerate(SCEN_ORDER):
        sr = er0 + i; rr = h + i
        gross_ref = f"{sref}!H{sr}"  # net of QS pre-XoL / tower basis
        cd.cell(row=rr, column=2, value=scen).font = F_CELL
        cd.cell(row=rr, column=3, value=f"=MIN({gross_ref},{ded_ref})").number_format = MONEY
        cd.cell(row=rr, column=4, value=f"=MAX(0,MIN({gross_ref}-{ded_ref},{lim_ref}))").number_format = MONEY
        cd.cell(row=rr, column=5, value=f"=MAX(0,{gross_ref}-{ded_ref}-{lim_ref})").number_format = MONEY
        cd.cell(row=rr, column=6, value=f"={ded_ref}").number_format = MONEY
        for cc in range(3, 7): cd.cell(row=rr, column=cc).font = F_CELL
        _alt_row(cd, rr, 2, 6, i % 2 == 0)
    return h, h + len(SCEN_ORDER) - 1

# ---- charts -----------------------------------------------------------------
def _chart_group_shape(cd, first, last):
    ch = BarChart(); ch.type = "col"; ch.grouping = "clustered"; ch.gapWidth = 65
    ch.title = "Gross loss by entity & scenario"
    cats = Reference(cd, min_col=2, min_row=first, max_row=last)
    data = Reference(cd, min_col=3, max_col=6, min_row=first - 1, max_row=last)
    ch.add_data(data, titles_from_data=True); ch.set_categories(cats)
    _style_axes(ch)
    for s, rgb in zip(ch.series, (PAL_FIHL, PAL_FUL, PAL_FIBL, PAL_FIID)): _colour(s, rgb)
    ch.legend.position = "r"
    return ch


def _chart_net_binding(cd, first, last, binding_idx=None):
    """Net loss by scenario (FIHL) — single series, binding bar emphasised."""
    ch = BarChart(); ch.type = "col"; ch.grouping = "clustered"; ch.gapWidth = 60
    ch.title = "Net loss by scenario — FIHL (worst case sets capital)"
    cats = Reference(cd, min_col=2, min_row=first, max_row=last)
    ch.add_data(Reference(cd, min_col=4, min_row=first - 1, max_row=last),
                titles_from_data=True)
    ch.set_categories(cats); _style_axes(ch)
    s = ch.series[0]
    _colour(s, NAVY_LT)
    n = last - first + 1
    for i in range(n):
        dp = DataPoint(idx=i)
        dp.graphicalProperties = GraphicalProperties(
            solidFill=(NAVY if i == binding_idx else NAVY_LT))
        s.data_points.append(dp)
    ch.legend = None
    return ch


def _chart_gross_net(cd, first, last):
    """Gross vs net by scenario (FIHL) — reinsurance benefit at group level."""
    ch = BarChart(); ch.type = "col"; ch.grouping = "clustered"; ch.gapWidth = 80
    ch.overlap = -10
    ch.title = "Gross vs net by scenario — FIHL (reinsurance benefit)"
    cats = Reference(cd, min_col=2, min_row=first, max_row=last)
    ch.add_data(Reference(cd, min_col=3, min_row=first - 1, max_row=last),
                titles_from_data=True)
    ch.add_data(Reference(cd, min_col=4, min_row=first - 1, max_row=last),
                titles_from_data=True)
    ch.set_categories(cats); _style_axes(ch)
    _colour(ch.series[0], PAL_GROSS); _colour(ch.series[1], PAL_NET)
    ch.legend.position = "r"
    return ch


def _chart_pareto(cd, first, last):
    bar = BarChart(); bar.type = "col"; bar.grouping = "clustered"; bar.gapWidth = 45
    bar.title = "Manufacturer concentration — Space Weather Pareto"
    cats = Reference(cd, min_col=2, min_row=first, max_row=last)
    expo = Reference(cd, min_col=3, min_row=first - 1, max_row=last)
    bar.add_data(expo, titles_from_data=True); bar.set_categories(cats)
    _style_axes(bar); _colour(bar.series[0], NAVY)
    line = LineChart()
    line.add_data(Reference(cd, min_col=4, min_row=first - 1, max_row=last), titles_from_data=True)
    line.set_categories(cats); line.y_axis.axId = 200
    line.y_axis.title = None; line.y_axis.numFmt = "0%"; line.y_axis.delete = False
    line.y_axis.scaling.min = 0; line.y_axis.scaling.max = 1; line.y_axis.crosses = "max"; line.y_axis.majorGridlines = None
    _colour(line.series[0], PAL_LINE, line=PAL_LINE); line.series[0].marker = Marker(symbol="circle", size=5)
    bar += line; bar.legend.position = "r"
    return bar


def _chart_delta(cd, first, last):
    ch = BarChart(); ch.type = "col"; ch.grouping = "clustered"; ch.gapWidth = 70
    ch.title = "Gross Δ% by Entity & Scenario  (▲ FIBL structural · ▼ FIID drop)"
    cats = Reference(cd, min_col=2, min_row=first, max_row=last)
    data = Reference(cd, min_col=3, max_col=6, min_row=first - 1, max_row=last)
    ch.add_data(data, titles_from_data=True); ch.set_categories(cats)
    _style_axes(ch, y_title="Gross Δ%", y_fmt='0.0%')
    ch.y_axis.scaling.min = -0.30
    ch.y_axis.scaling.max = 0.30
    for s, rgb in zip(ch.series, (PAL_FIHL, PAL_FUL, PAL_FIBL, PAL_FIID)): _colour(s, rgb)
    ch.legend.position = "r"
    return ch


def _chart_exposure_bridge(cd, first, last):
    ch = BarChart(); ch.type = "col"; ch.grouping = "clustered"; ch.gapWidth = 55
    ch.title = "Portfolio In-Force Exposure: Q4 2025 → Q1 2026"
    cats = Reference(cd, min_col=2, min_row=first, max_row=last)
    data = Reference(cd, min_col=3, min_row=first - 1, max_row=last)
    ch.add_data(data, titles_from_data=True); ch.set_categories(cats)
    _style_axes(ch, y_title="Exposure", y_fmt=MONEY_M)
    _colour(ch.series[0], PAL_TOTAL)
    ch.series[0].dLbls = DataLabelList(); ch.series[0].dLbls.showVal = True; ch.series[0].dLbls.numFmt = MONEY_M
    ch.legend = None
    return ch


def _chart_effectiveness(cd, first, last, entity):
    bar = BarChart(); bar.type = "col"; bar.grouping = "clustered"; bar.gapWidth = 95; bar.overlap = -10
    bar.title = f"{entity} — gross vs net retained, with retention %"
    cats = Reference(cd, min_col=2, min_row=first, max_row=last)
    bar.add_data(Reference(cd, min_col=3, min_row=first - 1, max_row=last), titles_from_data=True)
    bar.add_data(Reference(cd, min_col=5, min_row=first - 1, max_row=last), titles_from_data=True)
    bar.set_categories(cats); _style_axes(bar)
    _colour(bar.series[0], PAL_GROSS); _colour(bar.series[1], PAL_NET)
    line = LineChart(); line.add_data(Reference(cd, min_col=6, min_row=first - 1, max_row=last), titles_from_data=True)
    line.set_categories(cats); line.y_axis.axId = 200; line.y_axis.title = None; line.y_axis.numFmt = PCT
    line.y_axis.delete = False; line.y_axis.scaling.min = 0; line.y_axis.crosses = "max"; line.y_axis.majorGridlines = None
    _colour(line.series[0], PAL_LINE, line=PAL_LINE); line.series[0].marker = Marker(symbol="circle", size=6)
    line.series[0].dLbls = DataLabelList(); line.series[0].dLbls.showVal = True
    line.series[0].dLbls.showSerName = False; line.series[0].dLbls.showCatName = False
    line.series[0].dLbls.showLegendKey = False; line.series[0].dLbls.numFmt = PCT
    line.series[0].dLbls.dLblPos = "t"
    bar += line; bar.legend.position = "r"
    return bar


def _chart_tower(cd, first, last, entity):
    bar = BarChart(); bar.type = "col"; bar.grouping = "stacked"; bar.overlap = 100; bar.gapWidth = 70
    bar.title = f"{entity} — XoL tower utilisation by scenario"
    cats = Reference(cd, min_col=2, min_row=first, max_row=last)
    data = Reference(cd, min_col=3, max_col=5, min_row=first - 1, max_row=last)
    bar.add_data(data, titles_from_data=True); bar.set_categories(cats); _style_axes(bar)
    for s, rgb in zip(bar.series, (PAL_GROSS, PAL_LAYER, PAL_ABOVE)): _colour(s, rgb)
    line = LineChart(); line.add_data(Reference(cd, min_col=6, min_row=first - 1, max_row=last), titles_from_data=True)
    line.set_categories(cats); line.y_axis.axId = bar.y_axis.axId; line.y_axis.delete = True
    gp = GraphicalProperties(); gp.line = LineProperties(solidFill=PAL_LINE, w=12700); gp.line.dashStyle = "dash"
    line.series[0].graphicalProperties = gp; line.series[0].marker = Marker(symbol="none")
    bar += line; bar.legend.position = "r"
    return bar

# ---- orchestrator -----------------------------------------------------------
def build_charts_sheet(wb, summary="Summary", space_weather="Space Weather",
                       xol_terms=None, changes=None, portfolio="Portfolio",
                       charts_sheet="Charts", data_sheet="Chart Data",
                       binding=None):
    """Create the live Charts tab + formula-linked Chart Data tab."""
    xol_terms = xol_terms or DEFAULT_XOL
    summary_ws = wb[summary]
    sw_ws = wb[space_weather]
    rows = _locate_entity_rows(summary_ws)

    # Binding scenario (capital-setting). Prefer an explicit net-basis value;
    # else fall back to the largest gross (Summary col D is numeric).
    if binding is None:
        try:
            grs = [(_safe_num(summary_ws.cell(row=rows["FIHL"] + i, column=4).value), s)
                   for i, s in enumerate(SCEN_ORDER)]
            binding = max(grs, key=lambda x: (x[0] or 0))[1]
        except Exception:
            binding = None
    binding_idx = SCEN_ORDER.index(binding) if binding in SCEN_ORDER else None

    _safe_delete(wb, charts_sheet)
    _safe_delete(wb, data_sheet)
    cd = wb.create_sheet(data_sheet)
    ch = wb.create_sheet(charts_sheet)
    cd.sheet_view.showGridLines = False; ch.sheet_view.showGridLines = False

    cd["B2"] = "Chart Data"; cd["B2"].font = F_TITLE
    cd["B3"] = "Formula-linked backing tables for the Charts tab. No chart values are hard-coded."
    cd["B3"].font = F_SUB
    ch["B2"] = "Charts"; ch["B2"].font = F_TITLE
    ch["B3"] = ("Senior review pack — capital-basis risk shape \u00b7 reinsurance benefit "
                "\u00b7 concentration \u00b7 RI support.  Quarterly movement is on the WF tabs.")
    ch["B3"].font = F_SUB
    ch["B4"] = ("Live Excel charts linked to Chart Data; update the workbook and every "
                "visual redraws.  \u25c6 marks the worst-case scenario.")
    ch["B4"].font = F_CAP

    # Build data tables in curated senior order.
    dr = 5
    grp_first, grp_last = _table_group_gross_net(cd, summary, dr, rows, binding); dr = grp_last + 4
    pareto_first, pareto_last = _table_pareto(cd, space_weather, sw_ws, dr, n=10); dr = pareto_last + 4
    ful_eff_first, ful_eff_last = _table_effectiveness(cd, summary, dr, "FUL", rows["FUL"]); dr = ful_eff_last + 4
    fiid_eff_first, fiid_eff_last = _table_effectiveness(cd, summary, dr, "FIID", rows["FIID"]); dr = fiid_eff_last + 4
    t = xol_terms.get("FUL", DEFAULT_XOL["FUL"])
    ful_xol_first, ful_xol_last = _table_tower(cd, summary, dr, "FUL", t["deductible"], t["limit"], rows["FUL"]); dr = ful_xol_last + 4
    t = xol_terms.get("FIID", DEFAULT_XOL["FIID"])
    fiid_xol_first, fiid_xol_last = _table_tower(cd, summary, dr, "FIID", t["deductible"], t["limit"], rows["FIID"]); dr = fiid_xol_last + 4

    for col in range(1, 12): cd.column_dimensions[get_column_letter(col)].width = 16
    cd.column_dimensions["B"].width = 36
    cd.column_dimensions["H"].width = 20

    # Chart placement sequence requested by the user.
    chart_specs = [
        (_chart_net_binding(cd, grp_first, grp_last, binding_idx),
         "Capital view — net loss by scenario (FIHL). The worst-case scenario sets the RDS; "
         "scenarios are single-event and never summed."),
        (_chart_gross_net(cd, grp_first, grp_last),
         "Reinsurance benefit — gross vs net by scenario (FIHL). The gap is what the "
         "structure takes out."),
        (_chart_pareto(cd, pareto_first, pareto_last),
         "Concentration — manufacturer accumulation on the Space Weather basis, with "
         "cumulative share."),
        (_chart_effectiveness(cd, ful_eff_first, ful_eff_last, "FUL"),
         "RI support, FUL — gross vs retained net, with retention %."),
        (_chart_effectiveness(cd, fiid_eff_first, fiid_eff_last, "FIID"),
         "RI support, FIID — gross vs retained net, with retention %."),
        (_chart_tower(cd, ful_xol_first, ful_xol_last, "FUL"),
         "XoL tower, FUL — retained within deductible / ceded / above tower; dashed "
         "line = attachment."),
        (_chart_tower(cd, fiid_xol_first, fiid_xol_last, "FIID"),
         "XoL tower, FIID — retained within deductible / ceded / above tower; dashed "
         "line = attachment."),
    ]
    cr = 7; CHART_GAP = 30
    for chart, caption in chart_specs:
        _caption(ch, cr, caption)
        chart.height = 10.5; chart.width = 26.0
        if chart.legend is not None:
            chart.legend.position = "r"
        ch.add_chart(chart, f"C{cr + 3}")
        cr += CHART_GAP

    for col, width in {"A": 3, "B": 24, "C": 18, "D": 18, "E": 18, "F": 18, "G": 18, "H": 18, "I": 18, "J": 18, "K": 18, "L": 18}.items():
        ch.column_dimensions[col].width = width
    for rr in range(1, max(cr + 2, 280)):
        if ch.row_dimensions[rr].height is None:
            ch.row_dimensions[rr].height = 18
    for w in (ch, cd):
        w.page_setup.orientation = "landscape"; w.page_setup.fitToWidth = 1; w.page_setup.fitToHeight = 0
        w.sheet_properties.pageSetUpPr = PageSetupProperties(fitToPage=True)
        w.page_margins.left = 0.35; w.page_margins.right = 0.35; w.page_margins.top = 0.55; w.page_margins.bottom = 0.55
    ch.freeze_panes = "B5"; cd.freeze_panes = "B5"
    return ch
